finance/accounts/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from finance.accounts.views import (
    DashboardView, SettingsView, AccountTypeAddView, AccountTypeEditView,
    AccountTypeDeleteView, AccountView, AccountAddView, AccountEditView,
    AccountDeleteView, AccountTransactionView, TransactionAddView,
    TransactionEditView, TransactionDeleteView, TransactionImportView,
    TransactionImportConfirmView, DataYearlyDebit, DataYearlyDebitVsCredit
)


urlpatterns = patterns(
    "",
    url("^$", login_required(DashboardView.as_view()),
        name="accounts.dashboard"),
    url("^settings/$", login_required(SettingsView.as_view()),
        name="accounts.settings"),

    # data
    url("^data/yearly/debit/$",
        login_required(DataYearlyDebit.as_view()),
        name="data.yearly_debit"),
    url("^data/yearly/debit/vs/credit/$",
        login_required(DataYearlyDebitVsCredit.as_view()),
        name="data.yearly_debit_vs_credit"),

    # account types
    url("^settings/account_type/add/$",
        login_required(AccountTypeAddView.as_view()),
        name="accounts.account_type.add"),
    url("^settings/account_type/edit/(?P<pk>\d+)/$",
        login_required(AccountTypeEditView.as_view()),
        name="accounts.account_type.edit"),
    url("^settings/account_type/delete/(?P<pk>\d+)/$",
        login_required(AccountTypeDeleteView.as_view()),
        name="accounts.account_type.delete"),

    # accounts
    url("^list/$", login_required(AccountView.as_view()),
        name="accounts.account.list"),
    url("^add/$", login_required(AccountAddView.as_view()),
        name="accounts.account.add"),
    url("^edit/(?P<pk>\d+)/$", login_required(AccountEditView.as_view()),
        name="accounts.account.edit"),
    url("^delete/(?P<pk>\d+)/$", login_required(AccountDeleteView.as_view()),
        name="accounts.account.delete"),

    # transactions
    url("^transaction/list/(?P<pk>[\d]+)/$",
        login_required(AccountTransactionView.as_view()),
        name="accounts.transaction.list.by_account"),
    url("^transaction/add/$", login_required(TransactionAddView.as_view()),
        name="accounts.transaction.add"),
    url("^transaction/edit/(?P<pk>\d+)/$",
        login_required(TransactionEditView.as_view()),
        name="accounts.transaction.edit"),
    url("^transaction/delete/(?P<pk>\d+)/$",
        login_required(TransactionDeleteView.as_view()),
        name="accounts.transaction.delete"),
    url("^transaction/import/$",
        login_required(TransactionImportView.as_view()),
        name="accounts.transaction.import"),
    url("^transaction/import/confirm/$",
        login_required(TransactionImportConfirmView.as_view()),
        name="accounts.transaction.import.confirm"),
)

finance/core/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from finance.core.views import ProfileView

urlpatterns = patterns(
    "",
    url("^$", login_required(ProfileView.as_view()),
        name="profile.home"),
)

finance/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from finance.core.views import HomeView, RegisterView, ContactView


urlpatterns = patterns(
    '',
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^contact/$', ContactView.as_view(), name='contact'),
    url(r'^user/', include('django.contrib.auth.urls')),
    url(r'^accounts/', include('finance.accounts.urls')),
    url(r'^profile/', include('finance.core.urls')),
    url(r'^admin/', include(admin.site.urls)),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

finance/accounts/models.py
import datetime

from django.core.cache import cache
from django.db import models
from django.db.models import Q
from finance.core.models import Profile


class AccountTypeQuerySet(models.QuerySet):
    def yearly(self):
        return self.filter(yearly=True)

    def debits(self):
        return self.yearly().filter(default_type="DEBIT")

    def credits(self):
        return self.yearly().filter(default_type="CREDIT")


class AccountType(models.Model):
    TYPE_CHOICES = (
        ("DEBIT", "Debit"),
        ("CREDIT", "Credit"),
    )
    name = models.CharField(max_length=20)
    default_type = models.CharField(max_length=20, choices=TYPE_CHOICES,
                                    default="DEBIT")
    yearly = models.BooleanField(default=False)
    profile = models.ForeignKey(Profile)

    objects = AccountTypeQuerySet.as_manager()

    class Meta:
        ordering = ["name"]
        unique_together = (("name", "profile"), )

    def __unicode__(self):
        return self.name


class AccountQuerySet(models.QuerySet):
    def yearly(self):
        return self.filter(account_type__yearly=True)

    def clear_cache(self):
        for acct in self.yearly():
            acct.clear_cache()

    def debits(self):
        """Yearly accounts that are type DEBIT"""
        return self.yearly().filter(account_type__default_type="DEBIT")

    def credits(self):
        """Yearly accounts that are type CREDIT"""
        return self.yearly().filter(account_type__default_type="CREDIT")


class Account(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=250, blank=True)
    account_type = models.ForeignKey(AccountType)
    profile = models.ForeignKey(Profile)
    parent = models.ForeignKey('Account', null=True, blank=True,
                               limit_choices_to={"is_category": True})
    is_category = models.BooleanField(default=False)

    objects = AccountQuerySet.as_manager()

    class Meta:
        ordering = ["account_type", "name"]

    def __unicode__(self):
        return self.name

    @property
    def cache_key(self):
        return "account-{0}".format(self.pk)

    def clear_cache(self):
        cache.delete(self.cache_key)

    def balance(self):
        """Current balance of account"""
        balance = cache.get(self.cache_key)
        if balance is not None:
            return balance
        balance = 0
        if self.is_category:
            for acct in self.subaccounts():
                balance += acct.balance()
        else:
            trxs = self.transactions()
            if trxs:
                balance = trxs[0].balance
        cache.set(self.cache_key, balance)
        return balance

    def subaccounts(self):
        return Account.objects.filter(parent=self)

    def transactions(self, month=None):
        """Get all transactions associated with this account

        We want to clearly indicate the opposite account
        And maintain a running balance for each transaction
        """
        year = self.profile.year
        trxs = Transaction.objects.filter(
            Q(account_debit=self) | Q(account_credit=self)
        ).filter(date__year=year)
        if month is not None:
            trxs = trxs.filter(date__month=month)
        trxs = trxs.order_by("date")
        trx_list = []
        balance = 0
        for trx in trxs:
            if self == trx.account_credit:
                trx.amount = trx.amount * -1
            balance += trx.amount
            trx.balance = balance
            trx_list.append(trx)
        return trx_list[::-1]


class Transaction(models.Model):
    account_debit = models.ForeignKey(Account, related_name="debit",
                                      verbose_name="debit")
    account_credit = models.ForeignKey(Account, related_name="credit",
                                       verbose_name="credit")
    amount = models.DecimalField(decimal_places=2, max_digits=8)
    summary = models.CharField(max_length=100)
    description = models.CharField(max_length=250, blank=True)
    date = models.DateField()

    class Meta:
        ordering = ["-date", ]

    def __unicode__(self):
        return u"{summary} {amount}".format(
            summary=self.summary,
            amount=self.amount
        )

    def save(self, **kwargs):
        super(Transaction, self).save(**kwargs)
        profile = self.account_debit.profile
        if isinstance(self.date, datetime.date):
            year = self.date.year
        else:
            year = self.date[:4]
        cache.delete_many([
            self.account_debit.cache_key,
            self.account_credit.cache_key,
            "{0}-{1}-debits-vs-credits".format(
                profile.pk,
                year
            ),
            "{0}-{1}-debits-vs-credits".format(
                profile.pk,
                year
            ),
        ])

finance/core/models.py
import datetime

from django.contrib.auth.models import User
from django.db import models


def get_user_profile(user):
    return Profile.objects.get(user=user)


class Profile(models.Model):
    user = models.ForeignKey(User, unique=True)
    is_active = models.BooleanField(default=True)
    current_year = models.IntegerField(null=True)
    created = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return u"{0}".format(self.user.username)

    @property
    def year(self):
        if self.current_year is not None:
            return self.current_year
        return datetime.date.today().year

finance/accounts/forms.py
import os
import uuid

from django import forms
from django.conf import settings
from django.forms.formsets import formset_factory, BaseFormSet
from finance.accounts.models import (AccountType, Transaction,
                                     Account)
from finance.accounts.trx_import import TransactionsImport
from finance.accounts.utils import (get_account_choices,
                                    get_account_type_choices)
from finance.core.utils import get_year_choices


class AccountTypeForm(forms.ModelForm):
    class Meta:
        model = AccountType
        fields = ["name", "default_type", "yearly"]
        help_texts = {
            "yearly": "Account balance and transactions are limited "
            "to a specific year."
        }

    def clean(self):
        data = super(AccountTypeForm, self).clean()
        if "name" in data:
            if AccountType.objects.filter(name=data["name"]).exclude(
                    pk=self.instance.pk
            ).exists():
                raise forms.ValidationError("Name needs to be unique")


class AccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ["name", "description", "account_type", "parent",
                  "is_category"]

    def __init__(self, user, *args, **kwargs):
        super(AccountForm, self).__init__(*args, **kwargs)
        self.fields["account_type"].choices = get_account_type_choices(user)
        self.fields["parent"].choices = get_account_choices(user, True)


class TransactionImportForm(forms.Form):
    account_main = forms.ChoiceField()
    filename = forms.FileField()
    year = forms.ChoiceField(required=False)

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("user")
        super(TransactionImportForm, self).__init__(*args, **kwargs)
        self.fields["account_main"].choices = get_account_choices(self.user)
        self.fields["year"].choices = get_year_choices(True)

    def process_file(self):
        _, file_ext = os.path.splitext(self.files["filename"].name)
        filename = "{0}/imports/{1}{2}".format(settings.MEDIA_ROOT,
                                               uuid.uuid4(), file_ext)
        with open(filename, "wb+") as destination:
            for chunk in self.files["filename"].chunks():
                destination.write(chunk)
        parser = TransactionsImport(self.cleaned_data["account_main"],
                                    filename,
                                    year=self.cleaned_data.get("year"))
        parser.parse_file()
        return parser.transactions


class TransactionForm(forms.ModelForm):
    class Meta:
        model = Transaction
        exclude = ["description"]


class TransactionBaseFormSet(BaseFormSet):
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("user")
        super(TransactionBaseFormSet, self).__init__(*args, **kwargs)

    def _construct_form(self, i, **kwargs):
        form = super(TransactionBaseFormSet, self)._construct_form(i, **kwargs)
        account_choices = get_account_choices(self.user)
        form.fields["account_debit"].choices = account_choices
        form.fields["account_credit"].choices = account_choices
        if "DELETE" in form.fields:
            form.fields["DELETE"].label = "Duplicate"
        return form


TransactionImportFormSet = formset_factory(TransactionForm,
                                           can_delete=True, extra=0,
                                           formset=TransactionBaseFormSet)

TransactionFormSet = formset_factory(TransactionForm, extra=5,
                                     formset=TransactionBaseFormSet)

finance/core/forms.py
from django import forms
from django.conf import settings
from django.contrib.auth.models import User
from django.core.mail import send_mail
from finance.core.models import Profile


class ContactForm(forms.Form):
    subject = forms.CharField()
    email = forms.EmailField(required=False, help_text="(optional)")
    message = forms.CharField(widget=forms.Textarea)

    def send_email(self):
        send_mail("Hello from Finance", self.cleaned_data["message"],
                  self.cleaned_data.get("email", 'unknown'),
                  [settings.EMAIL_ADDRESS], fail_silently=True)


class RegisterForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())

    def clean(self):
        data = super(RegisterForm, self).clean()
        if data.get("password") and data.get("confirm_password"):
            if data["password"] != data["confirm_password"]:
                raise forms.ValidationError("Passwords do not match")
        return data

    def register(self):
        user = User.objects.create_user(self.cleaned_data['email'],
                                        self.cleaned_data['email'],
                                        self.cleaned_data['password'])
        Profile.objects.create(user=user)
        return user

finance/core/views.py
from django import forms
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.core.urlresolvers import reverse, reverse_lazy
from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView, FormView, UpdateView
from finance.accounts.models import Account
from finance.core.forms import RegisterForm, ContactForm
from finance.core.models import Profile
from finance.core.utils import get_year_choices


class HomeView(TemplateView):
    template_name = "home.html"


class ContactView(FormView):
    template_name = "contact.html"
    form_class = ContactForm

    def get_success_url(self):
        return reverse("contact")

    def get_context_data(self, **kwargs):
        kwargs = super(ContactView, self).get_context_data(**kwargs)
        kwargs["page"] = "contact"
        return kwargs

    def form_valid(self, form):
        form.send_email()
        messages.success(self.request,
                         u"Your message has been sent. Thank you!")
        return super(ContactView, self).form_valid(form)


class RegisterView(FormView):
    template_name = "registration/register.html"
    form_class = RegisterForm

    def get_success_url(self):
        return reverse("home")

    def form_valid(self, form):
        registered_user = form.register()
        user = authenticate(username=registered_user.username,
                            password=form.cleaned_data["password"])
        if user is not None:
            login(self.request, user)
        messages.success(self.request, "Successfully registered")
        return super(RegisterView, self).form_valid(form)


class ProfileView(UpdateView):
    model = Profile
    success_url = reverse_lazy("profile.home")
    fields = ["current_year"]

    def get_object(self):
        return get_object_or_404(Profile, user=self.request.user)

    def get_form(self, form_class):
        form = super(ProfileView, self).get_form(form_class)
        form.fields["current_year"].widget = forms.Select(
            choices=get_year_choices()
        )
        return form

    def form_valid(self, form):
        response = super(ProfileView, self).form_valid(form)
        Account.objects.filter(profile=self.object).clear_cache()
        messages.success(self.request, "Successfully updated current year"
                         " to {0}".format(form.cleaned_data["current_year"]))
        return response

finance/templates/accounts/account_add_modal.html
{% load bootstrap3 %}

<div class="modal fade" id="accountAddModal" tabindex="-1" role="dialog" aria-labelledby="accountAddModal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <form method="post" action="{% url 'accounts.account.add' %}" role="form" id="account-form">
        {% csrf_token %}
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4 class="modal-title" id="accountAddModalLabel">Add Account</h4>
        </div>
        <div class="modal-body" id="accountAddModalBody">
          {% bootstrap_form form_account %}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Add Account</button>
        </div>
      </form>
    </div>
  </div>
</div>

finance/templates/accounts/account_add_modal_button.html
<button type="button" class="btn btn-default" data-toggle="modal" data-target="#accountAddModal" title="Add Account">
  +
</button>

finance/templates/accounts/account_form.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block page-content %}
  {{ block.super }}

  <h2 class="sub-header">Save Account</h2>
  <div class="table-responsive col-md-4">
    <form method="post" action="" role="form">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% buttons %}
        <input type="submit" class="btn btn-success" value="Save Account" />
        <a href="{% url 'accounts.account.list' %}" class="btn btn-danger">Cancel</a>
      {% endbuttons %}
    </form>
  </div>
{% endblock page-content %}

finance/templates/accounts/account_list.html
{% extends "base.html" %}

{% block page-content %}
  {{ block.super }}
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>Type</th>
          <th>Balance</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        {% for account in object_list %}
          {% with depth=0 %}
            {% include "accounts/account_list_row.html" %}
          {% endwith %}
        {% endfor %}
      </tbody>
    </table>
    <p>
      <a href="{% url 'accounts.account.add' %}" class="btn btn-default">
        Add Account
      </a>
      <a href="{% url 'accounts.transaction.add' %}" class="btn btn-default">
        Add Transaction
      </a>
      <a href="{% url 'accounts.transaction.import' %}" class="btn btn-default">
        Import Transactions
      </a>
    </p>
  </div>
{% endblock page-content %}

finance/templates/accounts/account_list_row.html
{% load account_tags %}

<tr>
  <td>
    {{ "-"|repeat:depth }}
    {% if account.is_category %}
      <strong>{{ account.name }}</strong>
    {% else %}
      <a href="{% url 'accounts.transaction.list.by_account' account.pk %}">
        {{ account.name }}
      </a>
    {% endif %}
  </td>
  <td>{{ account.description }}</td>
  <td>{{ account.account_type.name }}</td>
  <td class="text-right">{{ account.balance|floatformat:"2" }}</td>
  <td>
    <a href="{% url 'accounts.account.edit' account.pk %}" class="btn btn-xs btn-default">Edit</a>
    <button type="button" class="btn btn-xs btn-danger" data-toggle="modal" data-target="#accountModalDelete{{ account.pk }}">Delete</button>
    <div class="modal fade" id="accountModalDelete{{ account.pk }}" tabindex="-1" role="dialog" aria-labelledby="accountModalDeleteLabel{{ account.pk }}" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <h4 class="modal-title" id="accountModalDeleteLabel{{ account.pk }}">Delete "{{ account.name }}" Account</h4>
          </div>
          <div class="modal-body">
            <p>Are you sure you want to delete this account?</p>
          </div>
          <div class="modal-footer">
            <form method="post" action="{% url 'accounts.account.delete' account.pk %}">
              {% csrf_token %}
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-danger">Delete Account</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </td>
</tr>

{% if account.is_category %}
  {% with depth=depth|add:"1" %}
    {% for account in account.subaccounts %}
      {% include "accounts/account_list_row.html" %}
    {% endfor %}
  {% endwith %}
{% endif %}

finance/templates/accounts/accounttype_form.html
{% extends "accounts/settings.html" %}
{% load bootstrap3 %}

{% block page-content %}
  <h1 class="page-header">Settings</h1>

  <h2 class="sub-header">Account Types</h2>
  <div class="table-responsive col-md-3">
    <form method="post" action="" role="form">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% buttons %}
        <input type="submit" class="btn btn-success" value="Save Account Type" />
        <a href="{% url 'accounts.settings' %}" class="btn btn-danger">Cancel</a>
      {% endbuttons %}
    </form>
  </div>
{% endblock page-content %}

finance/templates/accounts/dashboard.html
{% extends "base.html" %}
{% load staticfiles %}

{% block page-content %}
  {{ block.super }}
  <h2 class="sub-header">{{ debits_title }} vs {{ credits_title }}</h2>
  <div class="table-responsive">
    <div id="monthly-debit-vs-credit-charts">
      <img id="monthly-debit-vs-credit-charts-loader" src="{% static 'img/ajax-loader.gif' %}" />
    </div>
  </div>

  <h2 class="sub-header">Monthly {{ debits_title }}</h2>
  <div class="table-responsive">
    <div id="monthly-debit-charts">
      <img id="monthly-debit-charts-loader" src="{% static 'img/ajax-loader.gif' %}" />
    </div>
  </div>
{% endblock page-content %}

{% block page-js %}
  <script src="{% static 'js/d3.min.js' %}"></script>
  <script src="{% static 'js/colors.js' %}"></script>
  <script src="{% static 'js/dashboard.js' %}"></script>
  <script>
    $(function() {
        d3.json("{% url 'data.yearly_debit_vs_credit' %}", function(error, data) {
            HandleYearlyDebitVsCreditData(data);
        });

        d3.json("{% url 'data.yearly_debit' %}", function(error, data) {
            HandleYearlyDebitData(data);
        });
    });
  </script>
{% endblock page-js %}

finance/templates/accounts/settings.html
{% extends "base.html" %}

{% block page-menu %}{% endblock page-menu %}

{% block page-content %}
  <h1 class="page-header">Settings</h1>

  <h2 class="sub-header">Account Types</h2>
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>#</th>
          <th>Name</th>
          <th>Type</th>
          <th>Yearly</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        {% for account_type in account_types %}
          <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ account_type.name }}</td>
            <td>{{ account_type.get_default_type_display }}</td>
            <td>{{ account_type.yearly|yesno|capfirst }}</td>
            <td>
              <a href="{% url 'accounts.account_type.edit' account_type.pk %}" class="btn btn-sm btn-default">Edit</a>
              <button type="button" class="btn btn-sm btn-danger" data-toggle="modal" data-target="#accountTypeModalDelete{{ account_type.pk }}">Delete</button>
              <div class="modal fade" id="accountTypeModalDelete{{ account_type.pk }}" tabindex="-1" role="dialog" aria-labelledby="accountTypeModalDeleteLabel{{ account_type.pk }}" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                      <h4 class="modal-title" id="accountTypeModalDeleteLabel{{ account_type.pk }}">Delete "{{ account_type.name }}" Account Type</h4>
                    </div>
                    <div class="modal-body">
                      <p>Are you sure you want to delete this account type?</p>
                    </div>
                    <div class="modal-footer">
                      <form method="post" action="{% url 'accounts.account_type.delete' account_type.pk %}">
                        {% csrf_token %}
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-danger">Delete Account Type</button>
                      </form>
                    </div>
                  </div>
                </div>
              </div>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <p>
      <a href="{% url 'accounts.account_type.add' %}" class="btn btn-default">
        Add Account Type
      </a>
    </p>
  </div>
{% endblock page-content %}

finance/templates/accounts/transaction_form.html
{% extends "base.html" %}
{% load staticfiles bootstrap3 %}

{% block page-css %}
  {{ block.super }}
  <link rel="stylesheet" href="{% static 'css/datepicker.css' %}">
{% endblock page-css %}

{% block page-content %}
  {{ block.super }}

  <h2 class="sub-header">Save Transaction</h2>
  <div class="table-responsive col-md-4">
    <form method="post" action="" role="form">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% buttons %}
        <input type="submit" class="btn btn-success" value="Save Transaction" />
        <a href="{% url 'accounts.account.list' %}" class="btn btn-danger">Cancel</a>
      {% endbuttons %}
    </form>
  </div>
{% endblock page-content %}

{% block page-js %}
  <script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
  <script type="text/javascript">
    $(function() {
      $("#id_date").datepicker();
    });
  </script>
{% endblock page-js %}

finance/templates/accounts/transaction_form_multiple.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block page-content %}
  <h1 class="page-header">Transactions</h1>

  <h2 class="sub-header">Confirm Import Transactions</h2>
  <div class="table-responsive">
    <form method="post" action="{% url 'accounts.transaction.import.confirm' %}" role="form" class="form-inline">
      {% csrf_token %}
      {% bootstrap_form form.management_form %}
      <table class="table table-striped">
        <thead>
          <tr>
            <th>#</th>
            <th>Debit</th>
            <th>Credit</th>
            <th>Amount</th>
            <th>Summary</th>
            <th>Date</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          {% for f in form %}
            <tr>
              <td>{{ forloop.counter }}</td>
              <td>{% bootstrap_field f.account_debit layout="inline" %}</td>
              <td>{% bootstrap_field f.account_credit layout="inline" %}</td>
              <td>{% bootstrap_field f.amount layout="inline" %}</td>
              <td>{% bootstrap_field f.summary layout="inline" %}</td>
              <td>{% bootstrap_field f.date layout="inline" %}</td>
              <td>{% bootstrap_field f.DELETE layout="inline" %}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
      {% buttons %}
        <input type="submit" class="btn btn-success" value="Import Transactions" />
        <a href="{% url 'accounts.transaction.list' %}" class="btn btn-danger">Cancel</a>
      {% endbuttons %}
    </form>
  </div>
{% endblock page-content %}

finance/templates/accounts/transaction_formset.html
{% load bootstrap3 %}

{% csrf_token %}
{% bootstrap_form form.management_form %}
<table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>Debit</th>
      <th>Credit</th>
      <th>Amount</th>
      <th>Summary</th>
      <th>Date</th>
      {% if f.DELETE %}
        <th>Action</th>
      {% endif %}
    </tr>
  </thead>
  <tbody>
    {% for f in form %}
    <tr>
      <td>{{ forloop.counter }}</td>
      <td>
        {% bootstrap_field f.account_debit layout="inline" %}
        {% include "accounts/account_add_modal_button.html" %}
      </td>
      <td>
        {% bootstrap_field f.account_credit layout="inline" %}
        {% include "accounts/account_add_modal_button.html" %}
      </td>
      <td>{% bootstrap_field f.amount layout="inline" %}</td>
      <td>{% bootstrap_field f.summary layout="inline" %}</td>
      <td>{% bootstrap_field f.date layout="inline" %}</td>
      {% if f.DELETE %}
        <td>{% bootstrap_field f.DELETE layout="inline" %}</td>
      {% endif %}
    </tr>
    {% endfor %}
  </tbody>
</table>

finance/templates/accounts/transaction_import.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block page-content %}
  {{ block.super }}

  <h2 class="sub-header">Import Transactions</h2>
  <div class="table-responsive col-md-3">
    <form method="post" action="" role="form" enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% buttons %}
        <input type="submit" class="btn btn-success" value="Import Transactions" />
        <a href="{% url 'accounts.account.list' %}" class="btn btn-danger">Cancel</a>
      {% endbuttons %}
    </form>
  </div>
{% endblock page-content %}